version: '3.9'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "4318:4318"
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  opentelemetry:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - jaeger